CREATE TABLE HERO_LIST (
    ID NUMBER PRIMARY KEY,
    HERO_NAME VARCHAR2(50),
    POWER NUMBER,
    CITY VARCHAR2(50)
);

INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (1, '슈퍼맨', 9000, '메트로폴리스');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (2, '배트맨', 300, '고담');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (3, '아이언맨', 8500, '뉴욕');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (4, '캡틴아메리카', 7000, '뉴욕');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (5, '스파이더맨', 7500, '뉴욕');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (6, '토르', 9500, '아스가르드');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (7, '헐크', 9200, '데이턴');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (8, '원더우먼', 8800, '테미스키라');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (9, '플래시', 6000, '센트럴 시티');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (10, '블랙팬서', 7800, '와칸다');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (11, '닥터스트레인지', 8200, '뉴욕');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (12, '그린랜턴', 7700, '코스트 시티');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (13, '손오공', 50000, '서쪽 도시');
INSERT INTO HERO_LIST (ID, HERO_NAME, POWER, CITY) VALUES (14, '사이타마', 99999, 'Z시');
commit;
select * from HERO_LIST;
