-- CUSTOMERS 테이블 생성
CREATE TABLE CUSTOMERS (
    CUST_ID NUMBER(10) PRIMARY KEY, -- 고객번호 (기본 키)
    NAME VARCHAR2(50) NOT NULL      -- 이름
);

-- ORDERS 테이블 생성
CREATE TABLE ORDERS (
    ORDER_ID NUMBER(10) PRIMARY KEY,              -- 주문번호 (기본 키)
    CUST_ID NUMBER(10),                           -- 고객번호 (외래 키)
    ITEM VARCHAR2(100) NOT NULL,                  -- 상품
    CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUST_ID)
    REFERENCES CUSTOMERS(CUST_ID) -- 외래 키 제약 조건 설정
);

-- CUSTOMERS 테이블에 데이터 입력
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (1, '홍길동');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (2, '김철수');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (3, '박영희');

-- ORDERS 테이블에 데이터 입력
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (101, 1, '노트북');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (102, 2, '마우스');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (103, 1, '키보드');

INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (4, '이민준');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (5, '박서연');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (6, '최지우');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (7, '강현우');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (8, '윤하은');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (9, '임도윤');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (10, '송서아');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (11, '정시우');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (12, '한예은');
INSERT INTO CUSTOMERS (CUST_ID, NAME) VALUES (13, '오주원');

INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (104, 3, '모니터');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (105, 5, '스마트폰');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (106, 8, '태블릿');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (107, 2, '프린터');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (108, 11, '외장하드');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (109, 1, '웹캠');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (110, 7, '블루투스 이어폰');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (111, 4, 'USB 허브');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (112, 13, '보조배터리');
INSERT INTO ORDERS (ORDER_ID, CUST_ID, ITEM) VALUES (113, 9, '스피커');


-- 변경사항을 데이터베이스에 최종 반영
COMMIT;

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;