/*
# 오라클 제약조건(CONSTRAINTS)
1. 오라클의 제약조건은 테이블에 데이터를 입력, 수정, 삭제 할 때, 데이터의 무결성을 지키기 위해
    설정하는 강력한 규칙(위반데이터 위 입력, 수정, 삭제 처리되지 않는다) 이다.
* 제약조건이 없으면, 쓰레기 데이터가 쌓이게 된다.
2. 제약조건 5가지 종류
    1) PRIMARY KEY(PK) : 기본 키 - NOT NULL + UNIQUE
    2) NOT NULL(NN) : 필수 입력 - 해당 컬럼에 NULL을 허용하지 않음
    3) UNIQUE KEY(UK) : 중복 검사 - PK처럼 중복을 허용하지 않지만, NULL은 허용
    4) FOREIGN KEY(FK) : 외래 키(참조) - 다른 테이블(부모)의 PK나 UK를 참조
    5) CHECK(CK) : 데이터가 특정 조건을 만족하는지 검사. 정의된 CHECK 조건 (EX. GENDER IN('M', 'F'))를 통과해야함.
*/
-- 어벤져스 영웅 등록 테이블 만들기(PK, NN, UK, CK)
/*
1. HERO 테이블을 만든다
2. HERO_CODE : 영웅 코드 PK 
2. HERO_NAME : 이름 NN
3. EMAIL : 이메일 UK
5. AGE : 나이는 0살 초과하게 특정 범위로 지정하여 처리
*/
CREATE TABLE HERO(
    HERO_CODE NUMBER PRIMARY KEY, 
    HERO_NAEM VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    AGE NUMBER CHECK(AGE > 0)
);
SELECT * FROM HERO;
CREATE SEQUENCE HERO_SEQ
    START WITH 101;
SELECT HERO_SEQ.NEXTVAL FROM DUAL;
SELECT HERO_SEQ.CURRVAL FROM DUAL;

INSERT INTO HERO VALUES(HERO_SEQ.CURRVAL, '아이언맨', 'iron@stark.com', 40);
SELECT * FROM HERO;
-- CURRVAL로 입력 시 PK 위반
INSERT INTO HERO VALUES(HERO_SEQ.NEXTVAL, '캡틴아메리카', 'CAP@usa.com', 35);
-- 무결정 제약 조건 확인
SELECT * 
FROM ALL_CONSTRAINTS 
WHERE OWNER = 'SCOTT' 
AND TABLE_NAME= 'HERO' 
AND CONSTRAINT_NAME = 'SYS_C008283';
-- EX) PK 연습, STUDENTS01 테이블 STUD_ID로 NUMBER로 PRIMARY KEY 설정 후 테이블 생성
CREATE TABLE STUDENTS01(
    STUDE_ID NUMBER PRIMARY KEY
);
-- STUDENTS01_SEQ (시퀀스를 START WITH 1000)
CREATE SEQUENCE STUDENTS01_SEQ
    START WITH 1000;
-- STUDENTS01_SEQ.NEXTVAL, STUDENTS01_SEQ.CURRVAL
SELECT STUDENTS01_SEQ.NEXTVAL FROM DUAL;
SELECT STUDENTS01_SEQ.CURRVAL FROM DUAL;
-- STUDENTS01 테이블에 데이터 입력 시, PRIMARY KEY 제약조건이 걸릴 때, 벗어날 때를 구분하여 처리
-- 정상적 입력 
INSERT INTO STUDENTS01 VALUES(STUDENTS01_SEQ.CURRVAL);
INSERT INTO STUDENTS01 VALUES(STUDENTS01_SEQ.NEXTVAL);
-- 입력되지 않는 경우 (CURRVAL 두번쨰부터)
INSERT INTO STUDENTS01 VALUES(STUDENTS01_SEQ.CURRVAL);
-- INSERT INTO STUDENTS01 VALUES(STUDENTS01_SEQ.NEXTVAL);
SELECT * FROM STUDENTS01;
                