/*
# 데이터 창고의 보안키
1. 테이블과 테이블을 연결하는 가장 강력한 규칙
2. FOREIGN KEY는 두 테이블을 관계로 묶는 제약조건이다.
3. ORPHAN DATA를 원천 차단함. 뎅터의 일관성과 무결성을 지키는 핵심 장치
4. 기본형식
    컬럼명 데이터유형 FOREIGN KEY REFERENCES 참조테이블(참조컬럼)
    
*/
-- 부모테이블(VIP회원 명단)
CREATE TABLE DEPT10(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(50)
);
INSERT INTO DEPT10 VALUES(10, '홍길동');
INSERT INTO DEPT10 VALUES(20, '김길동');
INSERT INTO DEPT10 VALUES(30, '신길동');
COMMIT;
SELECT * FROM DEPT10;

CREATE TABLE EMP10(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(20),
    DEPTNO NUMBER(2) REFERENCES DEPT10(DEPTNO)
);
INSERT INTO EMP10 VALUES(1000, '홍길동', 10);
INSERT INTO EMP10 VALUES(1001, '김길동', 20);
INSERT INTO EMP10 VALUES(1002, '신길동', 30);
SELECT * FROM EMP10;